import json

from src.evaluation.generate import (
    GenerationConfig,
    _autogenerated_run_name,
    _make_run_id,
    _summarize_output,
)


def test_make_run_id_is_stable_for_the_same_run_name():
    run_name = "baseline_gemma_3_1b_it_unrelated_freeform_s42_20260326_deadbeef"
    assert _make_run_id(run_name) == _make_run_id(run_name)


def test_autogenerated_run_name_changes_when_config_changes():
    prompt_file = "prompts/v1/unrelated_freeform.jsonl"
    prompt_versions = ["v1"]

    baseline = GenerationConfig(
        model_name="google/gemma-3-1b-it",
        intervention_name="baseline",
        seed=42,
        temperature=1.0,
    )
    changed = GenerationConfig(
        model_name="google/gemma-3-1b-it",
        intervention_name="baseline",
        seed=42,
        temperature=0.7,
    )

    baseline_name = _autogenerated_run_name(baseline, prompt_file, prompt_versions)
    changed_name = _autogenerated_run_name(changed, prompt_file, prompt_versions)

    assert baseline_name != changed_name
    assert baseline_name.startswith("baseline_gemma_3_1b_it_unrelated_freeform_s42_")


def test_summarize_output_counts_resume_state_and_logprob_availability(tmp_path):
    output_path = tmp_path / "run.jsonl"
    records = [
        {
            "prompt_id": "p1",
            "category": "coding",
            "split": "main_eval",
            "finish_reason": "stop",
            "logprobs_available": True,
        },
        {
            "prompt_id": "p1",
            "category": "coding",
            "split": "main_eval",
            "finish_reason": "stop",
            "logprobs_available": False,
        },
        {
            "prompt_id": "p2",
            "category": "health",
            "split": "main_eval",
            "finish_reason": "length",
            "logprobs_available": False,
        },
    ]
    with open(output_path, "w") as fh:
        for record in records:
            fh.write(json.dumps(record) + "\n")

    prompts = [
        {"prompt_id": "p1"},
        {"prompt_id": "p2"},
        {"prompt_id": "p3"},
    ]
    summary = _summarize_output(output_path, prompts, expected_samples_per_prompt=2)

    assert summary["total_samples"] == 3
    assert summary["by_prompt"] == {"p1": 2, "p2": 1}
    assert summary["by_category"] == {"coding": 2, "health": 1}
    assert summary["by_logprob_availability"] == {"available": 1, "unavailable": 2}
    assert summary["by_completion_status"] == {"complete": 1, "missing": 1, "partial": 1}
